version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=springMessenger
    networks:
      backend:
        aliases:
          - "mysql"
networks:
  backend:
    driver: bridge